Refactor/course controller rework
Innoactive/Basic-UI-Component pull request #14
Opened 2021-02-18 15:45 UTC by tomwim

### Description
Rework of the course controller logic to separate logic from UI. The course controller now is intended to only spawn a course controller which is independent of the course controller menu. This allows the user to set a menu for the application independent of the course controller and rig. 
Additionally, the initialization of the Course now is done by the spawned Course Controller and not in the Menu anymore.

### Type of change
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected) ❓ 
- [X] This change requires a documentation update

### How Has This Been Tested?
Extended and created new CourseControllers to use a menu.
Tested for Default and Standalone Menu.
Change to custom prefabs.

### Aditional Notes
Might be a breaking change because prefabs changed. Not sure how to handle this.

2021-02-19 10:55 UTC, SimonTheSourcerer requested changes

2021-02-19 10:55 UTC, SimonTheSourcerer commented on Runtime/CourseController/Controllers/BaseCourseController.cs
> +        public virtual void SetupDone(GameObject courseControllerObject)
```suggestion
        /// </summary>
        public virtual void SetupDone(GameObject courseControllerObject)
```

2021-02-19 10:55 UTC, SimonTheSourcerer commented on Runtime/CourseController/Controllers/ICourseController.cs
> +        void SetupDone(GameObject courseControllerObject);
xml doc

2021-02-19 10:55 UTC, SimonTheSourcerer commented on Runtime/CourseController/InitCourseOnSceneLoad.cs
> +            InitTraining();
You can select the language with the menu loaded, is this way here still supporting switching the language?

2021-02-19 10:55 UTC, SimonTheSourcerer commented on Runtime/CourseController/CourseMenuSpawner.cs
> +        public void SetDefaultPrefab(GameObject prefab)
xml doc

2021-02-19 10:55 UTC, SimonTheSourcerer commented on Runtime/CourseController/Controllers/UIBaseCourseController.cs
> +        public abstract string CourseMenuPrefabName { get; }
xml doc

2021-02-19 13:33 UTC, Gusinuhe reviewed
It feels very weird that `CourseControllerMenu` has way more modifications than `StandaloneCourseMenu`, both scripts are supposed to be identical with the only difference that one uses Unity.UI stuff and the other TextMeshPro, we could even merge them if we rework the `AdvanceCourseController` UI to use TextMeshPro. ⚠️

2021-02-22 08:21 UTC, tomwim commented on Editor/CourseController/UI/CourseMenuSpawnerEditor.cs
> +            EditorGUILayout.ObjectField("Default prefab", defaultPrefabProperty.objectReferenceValue, typeof(GameObject), false);
I honestly would prefer it for the CourseController, too. It just gives you quicker access to see which prefab is gonna be spawned without looking for it somewhere. But I am fine either way

2021-02-22 10:17 UTC, tomwim commented
Unsure what to do with the CourseControllerMenu for now. 

Otherwise ready for re-review @Gusinuhe @SimonTheSourcerer

2021-02-22 13:49 UTC, SimonTheSourcerer approved these changes

2021-02-23 15:33 UTC, Gusinuhe approved these changes

2021-02-23 15:51 UTC, merged