Fix/workaround to trigger reload of cc
Innoactive/Basic-UI-Component pull request #38
Opened 2021-05-10 15:47 UTC by tomwim

### Description
When updating an old project the course controller might have missing scripts. A focus on the coursecontrollersetup is needed. This is a workaround to enforce this reload after scripts are loaded.

2021-05-10 21:05 UTC, tomwim commented on Runtime/CourseController/CourseControllerSetup.cs
> +                Selection.activeObject = setup;
Calling Setup here is probably the better way. But did not think about it before 🤔

2021-05-10 22:16 UTC, Gusinuhe requested changes
Still the same issue, an error message is thrown when playing the scene.

Test scenario:

An evaluator is trying to understand the creator, this person opens any example, plays it and finds the error and potentially no input.

2021-05-10 22:16 UTC, Gusinuhe commented on Runtime/CourseController/CourseControllerSetup.cs
> +using UnityEditor;
It might break during build or execution.

2021-05-11 07:09 UTC, tomwim commented on Runtime/CourseController/CourseControllerSetup.cs
> +                Selection.activeObject = setup;
Setup does not work

2021-05-11 08:41 UTC, Gusinuhe approved these changes

2021-05-11 08:52 UTC, merged